### ISSUE TITLE
[PR][UX] Improve description PR stats

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector-ci#29]
- X rectfied files

"Best off"

- X files changes by X Rector
- 30 files changed by Y level

**Comment by TomasVotruba** [comment]
Done in Rector

**Comment by JanMikes** [comment]
> Done in Rector
What does it mean?

I think this issue is still not resolved as it was about taking that data from Rector and showing them in PR body/comment.

**Comment by TomasVotruba** [comment]
In that case open issue at Rector with json code example. I don't remember what you needed

**Comment by JanMikes** [comment]
Yeah. I just do not understand why this issue was closed? It is something that still has to be done.

**Comment by TomasVotruba** [comment]
It needs clear description and right location.
